/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package package_rsbi_gui;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import methoden_rsbi.FrameManager;

/**
 *
 * @author JF
 */
public class JFrame_rsbi_main extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_rsbi_main
     */
    public JFrame_rsbi_main() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_search_main = new javax.swing.JButton();
        jButton_add_main = new javax.swing.JButton();
        jButton_logout_main = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("foogle");
        setResizable(false);

        jButton_search_main.setBackground(new java.awt.Color(204, 204, 204));
        jButton_search_main.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton_search_main.setForeground(new java.awt.Color(102, 102, 102));
        jButton_search_main.setText("SEARCH RECIPE");
        jButton_search_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_search_mainActionPerformed(evt);
            }
        });

        jButton_add_main.setBackground(new java.awt.Color(204, 204, 204));
        jButton_add_main.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton_add_main.setForeground(new java.awt.Color(102, 102, 102));
        jButton_add_main.setText("ADD RECIPE");
        jButton_add_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_mainActionPerformed(evt);
            }
        });

        jButton_logout_main.setBackground(new java.awt.Color(204, 204, 204));
        jButton_logout_main.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jButton_logout_main.setForeground(new java.awt.Color(102, 102, 102));
        jButton_logout_main.setText("LOGOUT");
        jButton_logout_main.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_logout_main.setBorderPainted(false);
        jButton_logout_main.setDefaultCapable(false);
        jButton_logout_main.setFocusPainted(false);
        jButton_logout_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_logout_mainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(296, Short.MAX_VALUE)
                        .addComponent(jButton_logout_main, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton_search_main, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_add_main, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_logout_main, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_search_main, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(jButton_add_main, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_search_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_search_mainActionPerformed
        JFrame searchwindow = FrameManager.getsearchrecipeFrame();
        searchwindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_search_mainActionPerformed

    private void jButton_add_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_mainActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame add =  FrameManager.getaddrecipeFrame();
        add.setVisible(true); 
        JFrame_rsbi_addrecipeform.jTextField_recipename_addrecipe.setText("");
        JFrame_rsbi_addrecipeform.jFormattedTextField_preptime_addrecipe.setText("");
        JFrame_rsbi_addrecipeform.jFormattedTextField_persons_addrecipe.setText("");
        JFrame_rsbi_addrecipeform.jTextArea_preparation_addrecipe.setText("");
        JFrame_rsbi_addrecipeform.jComboBox_difficulty_addrecipe.setSelectedIndex(-1);
        JFrame_rsbi_addrecipeform.jComboBox_category1_addrecipe.setSelectedIndex(0);
        JFrame_rsbi_addrecipeform.jComboBox_category2_addrecipe.setSelectedIndex(0);
        JFrame_rsbi_addrecipeform.jComboBox_category3_addrecipe.setSelectedIndex(0);
        JFrame_rsbi_addrecipeform.jComboBox_Ingredient_addrecipe.setSelectedIndex(-1);
        JFrame_rsbi_addrecipeform.jFormattedTextField_amount_addrecipe.setText("");
        JFrame_rsbi_addrecipeform.jComboBox_measurement_addrecipe.setSelectedIndex(-1);
        while(JFrame_rsbi_addrecipeform.jTable_ingredients_addrecipe.getRowCount() > 0){
                DefaultTableModel model = (DefaultTableModel) JFrame_rsbi_addrecipeform.jTable_ingredients_addrecipe.getModel();
                model.removeRow(0);
        }
    }//GEN-LAST:event_jButton_add_mainActionPerformed

    private void jButton_logout_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_logout_mainActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame login =  FrameManager.getloginFrame();
        //Reset des loginFrames
        JFrame_rsbi_login.jTextField_username_login.setText("");
        JFrame_rsbi_login.jPasswordField_login.setText("");
        //Sichtbarmachen
        login.setVisible(true);
    }//GEN-LAST:event_jButton_logout_mainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_rsbi_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_rsbi_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_rsbi_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_rsbi_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_rsbi_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_add_main;
    private javax.swing.JButton jButton_logout_main;
    private javax.swing.JButton jButton_search_main;
    // End of variables declaration//GEN-END:variables
}
