/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package package_rsbi_gui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import methoden_rsbi.FrameManager;
import methoden_rsbi.Verbindung;

/**
 *
 * @author JF
 */
public class JFrame_rsbi_registration extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_rsbi_registration
     */
    public JFrame_rsbi_registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_username_registration = new javax.swing.JTextField();
        jTextField_email_registration = new javax.swing.JTextField();
        jTextField_password_registration = new javax.swing.JTextField();
        jTextField_passwordconf_registration = new javax.swing.JTextField();
        jLabel_username_registration = new javax.swing.JLabel();
        jLabel_email_registration = new javax.swing.JLabel();
        jLabel_password_registration = new javax.swing.JLabel();
        jLabel_passwordconf_registration = new javax.swing.JLabel();
        jButton_registrate_registration = new javax.swing.JButton();
        jButton_Cancel_registration = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("foogle");
        setResizable(false);

        jTextField_username_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_username_registrationActionPerformed(evt);
            }
        });

        jTextField_email_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_email_registrationActionPerformed(evt);
            }
        });

        jTextField_password_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_password_registrationActionPerformed(evt);
            }
        });

        jTextField_passwordconf_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_passwordconf_registrationActionPerformed(evt);
            }
        });

        jLabel_username_registration.setText("Username");

        jLabel_email_registration.setText("Email");

        jLabel_password_registration.setText("Password");

        jLabel_passwordconf_registration.setText("Password Confirmation");

        jButton_registrate_registration.setText("Registrate");
        jButton_registrate_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registrate_registrationActionPerformed(evt);
            }
        });

        jButton_Cancel_registration.setText("Cancel");
        jButton_Cancel_registration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cancel_registrationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_password_registration, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_password_registration))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_email_registration, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_email_registration))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField_username_registration, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_username_registration))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton_registrate_registration)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Cancel_registration))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField_passwordconf_registration, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel_passwordconf_registration))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_username_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_username_registration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_email_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_email_registration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_password_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_password_registration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_passwordconf_registration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_passwordconf_registration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_registrate_registration)
                    .addComponent(jButton_Cancel_registration))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_username_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_username_registrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_username_registrationActionPerformed

    private void jTextField_email_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_email_registrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_email_registrationActionPerformed

    private void jTextField_password_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_password_registrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_password_registrationActionPerformed

    private void jTextField_passwordconf_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_passwordconf_registrationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_passwordconf_registrationActionPerformed

    private void jButton_Cancel_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cancel_registrationActionPerformed
        this.dispose();
        JFrame login = FrameManager.getloginFrame();
        login.setVisible(true);
    }//GEN-LAST:event_jButton_Cancel_registrationActionPerformed

    private void jButton_registrate_registrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registrate_registrationActionPerformed
        String username = jTextField_username_registration.getText();
        String email = jTextField_email_registration.getText();
        String password = jTextField_password_registration.getText();
        String password_conf = jTextField_passwordconf_registration.getText();
        boolean regcheck = false;
        
        try
        {
        
        Verbindung connect2DB = new Verbindung();
        regcheck = connect2DB.RegisterUser(username, email, password, password_conf);
        if (regcheck)
        {
            this.dispose();
            JFrame main = FrameManager.getmainFrame();
            main.setVisible(true);
            //Optional Wilkommensnachricht
            //JOptionPane.showMessageDialog(null, "Welcome!");
        }
        }
        catch(Exception e)
        {
            System.out.println("Fehler bei der Registration!");
            System.out.println("Fehler: " +e);
        }
       
    }//GEN-LAST:event_jButton_registrate_registrationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_rsbi_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_rsbi_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_rsbi_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_rsbi_registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_rsbi_registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cancel_registration;
    private javax.swing.JButton jButton_registrate_registration;
    private javax.swing.JLabel jLabel_email_registration;
    private javax.swing.JLabel jLabel_password_registration;
    private javax.swing.JLabel jLabel_passwordconf_registration;
    private javax.swing.JLabel jLabel_username_registration;
    private javax.swing.JTextField jTextField_email_registration;
    private javax.swing.JTextField jTextField_password_registration;
    private javax.swing.JTextField jTextField_passwordconf_registration;
    private javax.swing.JTextField jTextField_username_registration;
    // End of variables declaration//GEN-END:variables
}
