/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package package_rsbi_gui;

import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import methoden_rsbi.FrameManager;
import methoden_rsbi.Verbindung;

/**
 *
 * @author JF
 */
public class JFrame_rsbi_login extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_rsbi_login
     */
    public JFrame_rsbi_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_registration_login = new javax.swing.JButton();
        jButton_login_login = new javax.swing.JButton();
        jButton_connect_login = new javax.swing.JButton();
        jTextField_username_login = new javax.swing.JTextField();
        jLabel_username_login = new javax.swing.JLabel();
        jTextField_password_login = new javax.swing.JTextField();
        jLabel_password_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("foogle");
        setResizable(false);

        jButton_registration_login.setText("Registration");
        jButton_registration_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registration_loginActionPerformed(evt);
            }
        });

        jButton_login_login.setText("Login");
        jButton_login_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_login_loginActionPerformed(evt);
            }
        });

        jButton_connect_login.setText("Connect");
        jButton_connect_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_connect_loginActionPerformed(evt);
            }
        });

        jTextField_username_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_username_loginActionPerformed(evt);
            }
        });

        jLabel_username_login.setText("Username");

        jTextField_password_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_password_loginActionPerformed(evt);
            }
        });

        jLabel_password_login.setText("Password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_connect_login))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_username_login, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_password_login, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_username_login)
                                    .addComponent(jLabel_password_login)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_login_login, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_registration_login)))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_username_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_username_login))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_password_login)
                    .addComponent(jTextField_password_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_registration_login)
                    .addComponent(jButton_login_login))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(jButton_connect_login)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_connect_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_connect_loginActionPerformed
        // TODO add your handling code here:
        try
        {
            Verbindung connect2DB = new Verbindung();
            Connection conn2 = connect2DB.starteVerbindung();
            System.out.println("Verbindung erfolgreich aufgebaut!");
            conn2.close();
        }
        catch (Exception e)
        {
            System.out.println("Verbindung wurde nicht aufgebaut!");
            System.out.println("Fehler: "+e);
        }  
    }//GEN-LAST:event_jButton_connect_loginActionPerformed

    private void jTextField_username_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_username_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_username_loginActionPerformed

    private void jButton_login_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_login_loginActionPerformed
        // TODO add your handling code here:
        try
        {   
            // checks if Username and password are not empty
            if(!(jTextField_username_login.getText().equals("")) && !(jTextField_password_login.getText().equals("")))
            {
            Boolean logincheck = false;
            Boolean namecheck = false;
            Verbindung connect2DB = new Verbindung();
            namecheck = connect2DB.CheckName(jTextField_username_login.getText());
            if(namecheck)
            {
            logincheck = connect2DB.CheckPw(jTextField_username_login.getText(),jTextField_password_login.getText());
            if(logincheck)
            {
                //Wenn Login korrekt öffne main
                this.dispose();
                JFrame main = FrameManager.getmainFrame();
                main.setVisible(true);
            }
            }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Please enter your Username and Password!");
            }
        }
        catch(Exception e)
        {
        }
    }//GEN-LAST:event_jButton_login_loginActionPerformed

    private void jButton_registration_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registration_loginActionPerformed
        // TODO add your handling code here:
        this.dispose();
        JFrame registration = FrameManager.getregistrationFrame();
        registration.setVisible(true);
    }//GEN-LAST:event_jButton_registration_loginActionPerformed

    private void jTextField_password_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_password_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_password_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_rsbi_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_rsbi_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_rsbi_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_rsbi_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_rsbi_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_connect_login;
    private javax.swing.JButton jButton_login_login;
    private javax.swing.JButton jButton_registration_login;
    private javax.swing.JLabel jLabel_password_login;
    private javax.swing.JLabel jLabel_username_login;
    public static javax.swing.JTextField jTextField_password_login;
    public static javax.swing.JTextField jTextField_username_login;
    // End of variables declaration//GEN-END:variables
}
